### ISSUE TITLE
try-catch block fails to catch error with status-check

### ISSUE THREAD

**Issue by JEPanaton** [sguha-work/status-check#2]
Hello, I'm new to node.js and have attempted to use status-check to check a list of servers and display the result using http. The problem is that, when I add a nonexistent server to the test.txt file referenced in my code, I get this in the console: 
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND www.nonexistenturl.com www.nonexistenturl.com:80
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```
My code is as follows, where test.txt is a list of servers:
```
var http = require('http');

var server = http.createServer(function (request, response$
        var sc = require('status-check');
        try {
                sc.testLinkStatus("test.txt", function(dat$
                        console.log("Processed one.");
                        response.writeHead(200, {"Content-$
                        response.end(JSON.stringify(data));
                }, true);
        }
        catch (error) {
                console.log("Caught Error");
                console.log(error);
        }
});

server.listen(8000);
console.log("Server running at http://127.0.0.1:8000/");
```
Thanks for the help!

**Comment by CyberCyclone** [comment]
You've probably figured this out or not using this anymore.

The issue is that try catch doesn't work with callbacked functions, only the code it's directly referencing. The main issue is that this plugin doesn't make use of http error handling.
